# Generated by Django 5.2 on 2025-04-03 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=20)),
                ('datos_anterior', models.CharField(max_length=100)),
                ('datos_cambio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('obs', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'audtoria',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('contacto', models.CharField(max_length=20, verbose_name='Contacto')),
                ('tel_contacto', models.CharField(max_length=50, verbose_name='Tel. Contacto')),
                ('obs', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Confecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.clientes')),
            ],
            options={
                'db_table': 'confecciones',
            },
        ),
        migrations.CreateModel(
            name='Confecciones_detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tamano', models.CharField(max_length=10)),
                ('genero', models.CharField(choices=[('H', 'HOMBRE'), ('M', 'MUJER'), ('N', 'NIÑO')], default='H', max_length=1)),
                ('item_adicional', models.CharField(default='S', max_length=1)),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
                ('confecciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.confecciones')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.items', verbose_name='Item')),
            ],
            options={
                'db_table': 'confecciones_detalles',
            },
        ),
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(choices=[('C', 'CAMISETA'), ('S', 'SHORTS'), ('M', 'MEDIAS'), ('M', 'MUSCULOSA')], default='S', max_length=1)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
                ('confecciones_detalles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.confecciones_detalles')),
            ],
            options={
                'db_table': 'adicional',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
                ('confecciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.confecciones')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Pagos_detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
                ('pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.pagos')),
            ],
            options={
                'db_table': 'pagos_detalles',
            },
        ),
    ]
