# Generated by Django 5.2 on 2025-04-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviado', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('obs', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='confecciones_detalles',
            name='tamano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.tamano'),
        ),
    ]
