# Generated by Django 5.2 on 2025-04-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0002_tamano_alter_confecciones_detalles_tamano'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tamano',
            table='tamano',
        ),
    ]
