# Generated by Django 5.2 on 2025-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0003_alter_tamano_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='confecciones',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='confecciones_detalles',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagos_detalles',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tamano',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
